name: Deploy

# on:
#   push:
#     branches:
#       - master
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: intalling Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: checkout code
      uses: actions/checkout@v2

    - name: testing app
      run: go test ./...

    - name: build app 
      run: go build -o app-kaderisasi-go main.go

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "app-kaderisasi-go"
        target: "/var/www/go/test/ass"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /var/www/go/test/
          ls
        