name: Deploy

# on:
#   push:
#     branches:
#       - master

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...

    - name: deploy
      uses: appleboy/ssh-action@master
      with: 
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      script: |
        ls