name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-laters]
    
    runs-on: ${{ matrix.go-version }}

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with: 
        go-version: ${{ matrix.go-version }}
    
    -uses: actions/checkout@v2

    -name: Test
      run: go test ./...